---

- block:
    - validate:
        schema:
          type: object
          additionalProperties:
            - command
          properties:
            packages:
              type: array
              items:
                type: string
              default: []
            upgrade:
              type: boolean
              default: no
            user:
              type: boolean
              default: no
          required:
            - packages
            - upgrade
            - user
        instance: "{{ python }}"
      register: python_validated

    - set_fact:
        python_v: "{{ python_validated.result }}"

#    - name: "Install pip"
#      shell: "curl -sS https://bootstrap.pypa.io/get-pip.py | sudo {{ item.python }}"
#      args:
#        creates: "/usr/local/bin/{{ item.pip }}"
#        warn: no
#      loop:
#        - python: python2
#          pip: pip2
#        - python: python3
#          pip: pip3

    - name: "Install pip"
      apt:
        name:
          - python-pip
          - python3-pip
        state: present
      become: yes

    - block:
      - name: "Get pip options"
        set_fact:
          python_pip_options:
            - "{{ python_v.upgrade | ternary('--upgrade', None) }}"
            - "{{ python_v.user | ternary('--user', None) }}"

      - name: "Install pip packages"
        pip:
          name: "{{ python_v.packages }}"
          executable: "/usr/bin/{{ item }}"
          extra_args: "{{ python_pip_options | join(' ') }}"
        loop:
          - pip2
          - pip3

      when: python_v.packages | length

  tags:
    - python_pip
