---

- block:
    - validate:
        schema:
          type: object
          additionalProperties:
            - command
          properties:
            packages:
              type: array
              items:
                type: string
              default: []
          required:
            - packages
        instance: "{{ python }}"
      register: python_validated

    - set_fact:
        python_v: "{{ python_validated.result }}"

    - name: "Install pip3"
      shell: curl -sS https://bootstrap.pypa.io/get-pip.py | sudo python3
      args:
        creates: /usr/local/bin/pip3
        warn: no

    - name: "Install pip packages"
      pip:
        name: "{{ python_v.packages }}"
        executable: /usr/local/bin/pip3
        extra_args: --upgrade --user
      when: python_v.packages | length

  tags:
    - os_pip3
