---

- block:
    - validate:
        schema:
          type: object
          additionalProperties:
            - command
          properties:
            packages:
              type: array
              items:
                type: string
              default: []
            user:
              type: boolean
              default: no
            upgrade:
              type: boolean
              default: no
          required:
            - packages
        instance: "{{ python }}"
      register: python_validated

    - set_fact:
        python_v: "{{ python_validated.result }}"

    - name: "Install pip3"
      shell: curl -sS https://bootstrap.pypa.io/get-pip.py | sudo python3
      args:
        creates: /usr/local/bin/pip3
        warn: no

    - block
      - name: "Get pip options"
        set_fact:
          python_pip_options:
            - "{{ python_v.upgrade | ternary('--upgrade', None) }}"
            - "{{ python_v.user |ternary('--user', None) }}"

      - debug:
          msg: "{{ python_pip_options | join(' ') }}"

      - name: "Install pip packages"
        pip:
          name: "{{ python_v.packages }}"
          executable: /usr/local/bin/pip3
          extra_args: "{{ python_pip_options | join(' ') }}"
        become: "{{ not python_v.user }}"
      when: python_v.packages | length

  tags:
    - python_pip3
