---

- block:
    - validate:
        schema:
          type: object
          properties:
            command:
              type: string
              enum:
                - pip
          required:
            - command
        instance: "{{ python }}"

    - include_tasks: '{{ python.command }}.yml'
  tags:
    - python
